[build]
  publish = "public"
  command = "git submodule update --init --recursive && npm run clean && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--cache .npm-cache"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
